CREATE DATABASE infokanlokerdotcom;

USE infokanlokerdotcom;

CREATE TABLE detail_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) DEFAULT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE login_users (
    id INT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    FOREIGN KEY (id) REFERENCES detail_users(id) ON DELETE CASCADE
);
